version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./website:/var/www/sharpishly/website
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./website:/var/www/sharpishly/website
    env_file: .env

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
